"""Builds imports/twostorytails-instagram.json from captions read off the @twostorytails IG grid
(screenshots, newest first). Import it in the app: Settings > Import backup.

Cats: C = Cali (calico), N = Neo (white with grey on top), R = Ramses (dark grey striped),
D = Diego (Bengal, light brown and black). Tones: M meme, R relatable, F funny, W wholesome,
E educational, X multi-cat tie-in. Posts with no on-screen text are left out.
"""
import json
from datetime import datetime, timedelta, timezone

CATS = {'C': 'Cali', 'N': 'Neo', 'R': 'Ramses', 'D': 'Diego'}
TONES = {'M': 'Meme-style', 'R': 'Relatable', 'F': 'Funny', 'W': 'Wholesome', 'E': 'Educational', 'X': 'Multi-cat tie-in'}

# (caption, cats, tones) newest to oldest
POSTS = [
    ("Having a girl cat", "C", "F"),
    ("no one warns you that personal space becomes a completely foreign concept once you're a cat owner", "D", "R"),
    ("POV: you've never paid a bill in your life and it shows", "D", "M"),
    ("some days the only agenda is whatever my cat decides it is", "D", "W"),
    ("nothing humbles you like being loudly meowed at for food you just gave them ten minutes ago", "R", "R"),
    ("i've never had a relationship this codependent where only one of us is emotionally available", "D", "F"),
    ("some days i don't feel like i did much, but i showed up for my cat and that counts too", "D", "W"),
    ("I think my cats have taught me more about patience than any person ever has", "RD", "WX"),
    ("\"You're so spoiled\" God forbid i was adopted by child-free millenials that think im their birth child", "D", "M"),
    ("Non-negotiable habits as a cat dad", "C", "E"),
    ("cats have mastered the art of looking innocent 0.2 seconds after doing something insane", "C", "F"),
    ("They treat a cardboard box like a five star suite they personally designed", "RD", "FX"),
    ("I can't believe he has his own little organs, his own little brain and his own little thoughts", "D", "W"),
    ("Another long day of being the wifi password", "D", "M"),
    ("Cat body language cues you're probably missing", "R", "E"),
    ("he'll walk right past a $__ cat bed to sit in the wrapping it came in instead", "R", "R"),
    ("Started from the bottom now I have a house, two maids that serve me, and feeding on schedule", "C", "M"),
    ("POV: You are living someone's best life", "R", "M"),
    ("my cat has one job and making sure I never finish a task uninterrupted", "C", "R"),
    ("How we manage 4 cats across 2 floors without losing our minds", "RD", "EX"),
    ("some people have alarm clocks, I have cats who decided breakfast at 6am is non-negotiable", "D", "R"),
    ("in your 20's & 30's you should put your money aside for savings... here are my savings", "DR", "FX"),
    ("Window setups that changed my cats' entire mood", "N", "E"),
    ("My cat has access to an entire house and still chooses to sit here", "R", "R"),
    ("i've never felt more chosen than the moment a cat decides you're their person", "D", "W"),
    ("he demands to be let into a room and then immediately asks to be let back out, stay toxic", "N", "F"),
    ("my cats have main character energy and i'm just the guy who buys the food", "DR", "FX"),
    ("Never stop begging.. you only need one yes to succeed", "D", "F"),
    ("Signs your cat is in pain that are easy to miss", "R", "E"),
    ("POV: You live in a multi-cat household", "RD", "MX"),
    ("Yeah, therapy is cool, but have you ever tried this?", "D", "W"),
    ("there's no version of working from home where my cat isn't somehow involved in the job", "R", "R"),
    ("What it's like to have no bills to pay", "DR", "MX"),
    ("When my cat finds out we're spending the day rotting in bed", "N", "R"),
    ("Thinking of getting a Savannah cat? Read this before you do", "R", "E"),
    ("Decoding cat tail language: your cat's tail is basically subtitles for their mood", "", "E"),
    ("When the spare human says they already fed you", "D", "F"),
    ("How I talk to my cat every night before bed", "D", "W"),
    ("every 2 cat household has one of each", "D", "M"),
    ("Day 89 of posting my cat online so he can start paying rent", "D", "F"),
    ("Every pet parent has accidentally created a daily ritual and now lives under a tiny furry dictator", "D", "R"),
    ("The cat I got to emotionally support me", "D", "F"),
    ("Domestic cats vs exotic cats: same species, different operating systems", "", "EX"),
    ("And for the lady... perhaps a cat bed?", "", "F"),
    ("My cats trying to convince me nobody has fed them today", "R", "R"),
    ("daily reminder that no matter how tired you are after work, your cat has been waiting all day to be with you.", "D", "W"),
    ("I've been lying to my cat for years. Every time he meows I say \"I know\". But I don't know. I don't even have a clue.", "R", "F"),
    ("When dad defends you no matter what", "R", "W"),
    ("When dad is shouting at someone named \"forgodsakesits5amstopmeowing\" But my name is literally Ramses.", "R", "F"),
    ("My cats when they get supervised outdoor time", "N", "M"),
    ("When you ask your man for back rubs but he passes out after 3 minutes", "RD", "FX"),
    ("when his wittle brain says potty time but his firmware is stuck on \"hooman toilet mode\"", "R", "F"),
    ("I'm no therapist, but have you tried doing this?", "D", "W"),
    ("\"You're so spoiled\" God forbid I was adopted by a millenial that thinks I'm their literal birth child", "N", "M"),
    ("What is the meaning of life?", "C", "M"),
    ("\"Your house must be so peaceful without kids\"", "RD", "MX"),
    ("POV: My cat proposing the idea of another nap after just waking up from his previous one", "D", "M"),
    ("how do you explain this to someone who doesn't like cats", "D", "W"),
    ("When you have multiple cats, one cat is always plotting to get food and the others are just along for the ride", "R", "RX"),
    ("Me anytime my cat drinks bc that means he had a thought that he was thirsty & made the conscious choice to walk to his water bowl", "D", "W"),
    ("There is currently (1) cat in line for bed. Estimated wait time: 67 minutes", "R", "F"),
    ("when you are giving your first cat attention and the second one notices", "N", "RX"),
    ("When your brother HATES being touched but your only purpose in life is to annoy him", "RD", "FX"),
    ("POV: Dad placed your treats in highly inconvenient contraptions and now you have to gruellingly find them", "R", "M"),
    ("I don't want to bother my brother", "R", "FX"),
    ("Our cat trying to convince us nobody has fed him today", "R", "R"),
    ("Cats after using the litter box:", "D", "M"),
    ("Me when I see my cat do anything:", "C", "M"),
    ("I got called pretty today", "D", "F"),
    ("When your hoomans decide to get a second cat without asking", "D", "RX"),
    ("POV: The holiday guests have left and you can finally come out from hiding", "R", "M"),
    ("When an email at work says \"any update on this?\" and the update is that I forgot it existed", "N", "R"),
    ("On today's episode of fat and jobless:", "N", "F"),
    ("My cats acting like they just worked a gruelling 12 hour shift", "D", "R"),
    ("when dad starts complaining about his job but you literally only know your own name and the sound of food being opened", "D", "F"),
    ("\"Your house must be so calm without kids\" The house:", "RD", "MX"),
    ("Meowed until everyone woke up and then went back to sleep. STAY TOXIC", "N", "F"),
    ("When the hooman says dinner might be slightly late", "N", "F"),
    ("When they say cats are a reflection of their owners and mine is always hungry and anxious", "R", "R"),
    ("my brain when I'm asked to explain anything", "N", "M"),
    ("When your hooman picks you up for cuddles", "D", "W"),
    ("My cats the moment they hear me breathe in the morning", "R", "R"),
    ("Multi-cat households be like", "N", "MX"),
    ("When you tell your cat no more treats but he sees you opening your third bag of takis", "R", "F"),
    ("The official cat \"I love you\"", "D", "W"),
    ("Our male son Diego showing his instinctual motherly love", "DR", "WX"),
    ("Another hard day at work being the home wifi password", "D", "M"),
    ("Still can't believe my cat has his own little brain, just planning his day using his own little mind and with his own little thoughts.", "R", "W"),
    ("When you're forced to put up with daddy's antics because he's your treats dealer", "D", "F"),
    ("2 cat households at least 4 times per day", "RD", "MX"),
    ("Give me second breakfast", "D", "M"),
    ("When Ramses' precious snooze makes you overlook the 3am zoomies", "R", "W"),
    ("How I look at my man after annoying him for absolutely no reason.", "R", "F"),
    ("My cat, 90% chaos, 10% this.", "D", "M"),
    ("Me unloading the entire week's drama to my cat whose only advice is to fill his bowl.", "D", "R"),
    ("Turns out the secret ingredient to making the perfect biscuits is...", "RD", "FX"),
    ("When your brother steals your bed so you have to curse him", "DR", "FX"),
    ("When the intrusive thoughts fall in sync.", "RD", "MX"),
    ("Don't make eye-contact, Don't make eye-contact, Don't make eye-contact...", "C", "F"),
    ("Just a mama taking care of her sleepy son", "DR", "WX"),
    ("Neo's got that undeniable charm. Just ask him.", "N", "W"),
    ("When your spoiled cat is forced to share the cat tree", "RD", "FX"),
    ("When they say 'sell your feet pics' but you're just a...", "C", "M"),
    ("Don't let the face fool you. She's taking notes.", "C", "F"),
    ("Hired an eating machine and a supervisor. The machine is over-performing. The supervisor has... notes.", "N", "FX"),
    ("The neighbourhood watch comitee takes its job very seriously", "RD", "FX"),
    ("My cat when I tell him he has to contribute to the household... so he started training for his influencer career.", "D", "F"),
    ("The audacity.", "R", "F"),
    ("Zzzz....", "N", "W"),
    ("Nothing to see here, just being a berry good girl ❤️🍓", "C", "W"),
    ("POV: You live in a multi-cat household", "DR", "MX"),
    ("Deep thawts...", "D", "M"),
    ("Me: scrubs the litter box till it's spotless. Ramses: And I took that personally.", "R", "F"),
    ("When you find out hoomans don't have to 'sit' or 'stay' for snacks", "D", "F"),
    ("Your outie prefers dry food.", "D", "M"),
    ("Neo's favourite nap spots", "N", "E"),
    ("Serious business happening here. Probably discussing their next 3 AM wake-up call for me....", "N", "F"),
]

now = datetime.now(timezone.utc)
clips = []
for i, (caption, cats, tones) in enumerate(POSTS):
    clips.append({
        'id': 'ig%03d' % (len(POSTS) - i),       # oldest post is ig001
        'desc': caption,
        'status': 'posted',
        'created': (now - timedelta(minutes=i)).isoformat(timespec='seconds').replace('+00:00', 'Z'),
        'scheduledDate': '',                    # posting dates aren't visible on the grid
        'platform': 'Instagram',
        'selectedTones': [TONES[t] for t in tones],
        'catTags': [CATS[c] for c in cats],
        'archived': False,
    })

with open('imports/twostorytails-instagram.json', 'w') as f:
    json.dump({'exportedFrom': 'TwoStoryCaptions', 'source': 'Instagram grid @twostorytails', 'clips': clips}, f, ensure_ascii=False, indent=2)
print(len(clips), 'posts')
for c in CATS.values():
    print(c, sum(c in x['catTags'] for x in clips))
